# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test-public:
    runs-on: ubuntu-22.04
    environment: PYTEST

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: 'Create env file'
      run: |
        echo '${{ secrets.ENV_FILE }}' > .env
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest --auth public

  test-member:
    runs-on: ubuntu-22.04
    environment: PYTEST

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: 'Create env file'
      run: |
        echo '${{ secrets.ENV_FILE }}' > .env
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test member access to member area
      run: |
        pytest --auth member

  test-author:
    runs-on: ubuntu-22.04
    environment: PYTEST

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: 'Create env file'
      run: |
        echo '${{ secrets.ENV_FILE }}' > .env
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test author access to member area
      run: |
        pytest --auth author

  test-admin:
    runs-on: ubuntu-22.04
    environment: PYTEST

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: 'Create env file'
      run: |
        echo '${{ secrets.ENV_FILE }}' > .env
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test admin access to member area
      run: |
        pytest --auth admin
